/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author adita
 */
public class loginreg extends javax.swing.JFrame {

    /**
     * Creates new form loginreg
     */
    public loginreg() {
        initComponents();
    }
    void clear(){
         tfusr.setText(" ");
         tfpswd.setText(" ");
         tfname.setText(" ");
         tfmail.setText(" ");
         tfphone.setText(" ");
        
    }
    void Visibility(boolean  b){
        lblname.setVisible(b);
        lblmail.setVisible(b);
        lblphone.setVisible(b);
        tfname.setVisible(b);
        tfmail.setVisible(b);
        tfphone.setVisible(b);
        if(b){
            iblmain.setText("Regester");
            btnlogin.setText("already have a account");
        }else{
            iblmain.setText("Login");
            btnlogin.setText("Login");
            
        }
    }
    void LoginCall(String usr,String pswd){
        boolean flag =false;
        try{
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection( "jdbc:mysql://localhost:3306/logins","root","panda");
            Statement stmt = conn.createStatement();
            String qrry ="select * from logindetails where username=\""+ usr +"\"and password=\"" + pswd+ "\";";
            ResultSet rs= stmt.executeQuery(qrry); 
            while(rs.next()){
                flag = true;
                
            }
            if(flag){
                JOptionPane.showMessageDialog(null,"login success");
                new admin2().setVisible(true);
                
                
            }
            else{
                JOptionPane.showMessageDialog(null,"invalid username|password");
            }
        }catch(HeadlessException | ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null,"error in connection"+ex);
        
        }
    }
    void Registercall(String usr,String pswd,String name,String mail,String phone){
            try{
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection( "jdbc:mysql://localhost:3306/logins","root","panda");
            Statement stmt = conn.createStatement();
            String qrry ="insert into logindetails values("
                    +"'"+usr+"',"
                    +"'"+pswd+"',"
                    +"'"+name+"',"
                    +"'"+mail+"',"
                    +"'"+phone+"'"
                    +")";
            
           stmt.executeUpdate(qrry); 
           stmt.close();
           conn.close();
           JOptionPane.showMessageDialog(null,"successfully register");
        }catch(HeadlessException | ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null,"error in connection"+ex);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iblmain = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfusr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfpswd = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        lblmail = new javax.swing.JLabel();
        tfmail = new javax.swing.JTextField();
        tfphone = new javax.swing.JTextField();
        lblphone = new javax.swing.JLabel();
        btnreg = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        bnclear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        iblmain.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        iblmain.setText("REGISTRATION");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newpackage/icon-for-on-line-registration-vector-19190227.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newpackage/icon-for-on-line-registration-vector-19190227.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iblmain)
                .addGap(164, 164, 164)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(645, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(iblmain, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel4)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(204, 255, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("username");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 41, 184, 36));
        jPanel2.add(tfusr, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 41, 213, 36));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("password");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 95, 184, 36));
        jPanel2.add(tfpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 95, 213, 36));

        lblname.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblname.setText("name");
        lblname.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 144, 184, 36));
        jPanel2.add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 144, 213, 36));

        lblmail.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblmail.setText("email");
        lblmail.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(lblmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 193, 184, 36));
        jPanel2.add(tfmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 193, 213, 36));
        jPanel2.add(tfphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 236, 213, 36));

        lblphone.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblphone.setText("phone");
        lblphone.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(lblphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 236, 184, 36));

        btnreg.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnreg.setText("register");
        btnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregActionPerformed(evt);
            }
        });
        jPanel2.add(btnreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 34));

        btnlogin.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnlogin.setText("already have a account");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel2.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, 34));

        bnclear.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bnclear.setText("clear");
        bnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnclearActionPerformed(evt);
            }
        });
        jPanel2.add(bnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 306, -1, 34));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregActionPerformed
            // TODO add your handling code here:
             Registercall(tfusr.getText(),tfpswd.getText(),tfname.getText(),tfmail.getText(), tfphone.getText());   
            if(iblmain.getText().equals("Register")){ 
                
                if(tfusr.getText() .length()==0 ||tfpswd.getText() .length()==0 ||tfname.getText().length()==0 ||tfmail.getText() .length()==0 ||
                        tfphone.getText() .length()==0){
                        JOptionPane.showMessageDialog(null,"fill all details");
                }else{
                        Registercall(tfusr.getText(),tfpswd.getText(),tfname.getText(),tfmail.getText(), tfphone.getText());     
                }
            }
            Visibility(true);
    }//GEN-LAST:event_btnregActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
       
        if(iblmain.getText().equals("Login")){            
            if(tfusr.getText() .length()==0 ||tfpswd.getText() .length()==0){
                JOptionPane.showMessageDialog(null,"fill all details");   
            }
            else{
                LoginCall(tfusr.getText(),tfpswd.getText());
            }
        }
           Visibility(false);  
    }//GEN-LAST:event_btnloginActionPerformed

    private void bnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnclearActionPerformed
  clear();
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bnclearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new adfrm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new loginreg().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnclear;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnreg;
    private javax.swing.JLabel iblmain;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphone;
    private javax.swing.JTextField tfmail;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfphone;
    private javax.swing.JTextField tfpswd;
    private javax.swing.JTextField tfusr;
    // End of variables declaration//GEN-END:variables
}
